version: '3.0'

services:
  nginx:
    restart: unless-stopped
    image: nginx
    ports:
    - 80:80
    - 443:443
    #    network_mode: host
    volumes:
    - /srv/nginx/nginx.conf:/etc/nginx/nginx.conf
    - /srv/nginx/conf.d:/etc/nginx/conf.d
    - /srv/nginx/html:/usr/share/nginx/html
    - /var/log/nginx:/var/log/nginx

    #    environment:
    #    - NGINX_HOST=your.domain
    #    - NGINX_PORT=80
