version: '3.0'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - /srv/mongo/data/db:/data/db
    ports:
    - 27018:27017
    command: mongod --smallfiles --logpath=/dev/null
